package:
    name: brain-py
    version: "1.0.3"

source:
    path: ../../

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    host:
        - python
        - pip
    run:
        - python
        - numpy>=1.13
        - sympy>=1.2
        - numba>=0.50
        - matplotlib>=3.0
        - setuptools>=40.0.0

test:
  imports:
    - brainpy

about:
    home: https://github.com/PKU-NIP-Lab/BrainPy
    license: GPL-3.0
    summary: 'A simulation toolbox for researches in computational neuroscience and brain-inspired computation.'
    description: |
        BrainPy is a lightweight framework based on the latest Just-In-Time (JIT)
        compilers (especially [Numba](https://numba.pydata.org/)). The goal of
        BrainPy is to provide a unified simulation and analysis framework for neuronal
        dynamics with the feature of high flexibility and efficiency. BrainPy is
        flexible because it endows the users with the fully data/logic flow control.
        BrainPy is efficient because it supports JIT acceleration on CPUs  and GPUs.
    dev_url: https://github.com/PKU-NIP-Lab/BrainPy
    doc_url: https://brainpy.readthedocs.io/en/latest/
    doc_source_url: https://github.com/PKU-NIP-Lab/BrainPy/blob/master/README.md
