# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Make documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  make_docs:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements-doc.txt ]; then pip install -r requirements-doc.txt; fi
          pip uninstall brainpy -y
          python setup.py install
      - name: Make docs
        run: |
          cd brainpy_docs/docs
