# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Make documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  make_docs:
    runs-on:
      group: Default
      labels: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          architecture: "x86"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements-doc.txt ]; then pip install -r requirements-doc.txt; fi
          pip uninstall brainpy -y
          python setup.py install
      - name: Make docs
        run: |
          cd brainpy_docs/docs
